<?php

namespace AppBundle\Repository;

/**
 * chauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireRepository extends \Doctrine\ORM\EntityRepository
{



}
