<?php

namespace AppBundle\Repository;

/**
 * msg_chRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class msg_chRepository extends \Doctrine\ORM\EntityRepository
{
}
