<?php

namespace AppBundle\Repository;

/**
 * MsgChRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgChRepository extends \Doctrine\ORM\EntityRepository
{
}
